---
title: "R Stats Cookbook - 05 Nonparametric Methods"
output: html_notebook
---

# 01 Wilcoxon

```{r}
data = read.csv("https://raw.githubusercontent.com/PacktPublishing/R-Statistics-Cookbook/master/Chapter05/heights.csv") 
data$Sample = as.factor(data$Sample) 
wilcox.test(Height ~ Sample,data=data) 
```

```{r}
data = read.csv("https://raw.githubusercontent.com/PacktPublishing/R-Statistics-Cookbook/master/Chapter05/pre_post_employee.csv") 
wilcox.test(data$post_bonus, data$pre_bonus,paired=TRUE) 
```
# 02 Nonparametric ANOVA

```{r}
library(FSA) 
library(dplyr) 

t     = read.csv("https://raw.githubusercontent.com/PacktPublishing/R-Statistics-Cookbook/master/Chapter05/anova__lot_type.csv") 
kruskal.test(Result ~ Food.Type,data=t)

dunnTest(Result ~ Food.Type,data=t) 
```

# 03 Spearman

```{r}
x = seq(1,100) 
y = 20/(1+exp(x-50)) 
plot(x,y) 
```


```{r}
cor.test( ~ x + y, method = "spearman",conf.level = 0.95) 
```

```{r}
cor.test( ~ x + y, method = "pearson",conf.level = 0.95) 
```

```{r}
x = seq(1,100) 
y = sapply(x,function(x){(runif(1)-0.5)*10 + 20/(1+exp(x-50))})  
plot(x,y) 
```

```{r}
cor.test( ~ x + y, method = "spearman",conf.level = 0.95) 
```

```{r}
cor.test( ~ x + y, method = "pearson",conf.level = 0.95) 
```

```{r}
salary=c(10,50,45,87,69,100) 
educ_level=c(1,2,3,4,5,6) 
cor.test( ~ salary + educ_level, method = "spearman",conf.level = 0.95) 
```
# 04 LOESS Regression

```{r}
data = read.csv("https://raw.githubusercontent.com/PacktPublishing/R-Statistics-Cookbook/master/Chapter05/price__sales.csv") 
model_loess1 = loess(data$sales~data$price,  span = 2/3, degree = 2, family = c("gaussian")) 
model_loess2 = loess(data$sales~data$price,  span = 0.1, degree = 2, family = c("gaussian")) 

loess1_wrapper <- function(x){ 
  return (predict(model_loess1,x)) 
}  

loess2_wrapper <- function(x){ 
  return (predict(model_loess2,x)) 
} 

loess1_wrapper(5)   - loess1_wrapper(10)
loess1_wrapper(10)  - loess1_wrapper(15)
```

```{r}
plot(data$price,data$sales) 
curve(loess1_wrapper,add=TRUE,col="red",lwd=3) 
curve(loess2_wrapper,add=TRUE,col="blue",lwd=3) 
legend(17.7, 0.5, legend=c("span=0.75", "span=0.1"),col=c("red", "blue"), lty=1:1, cex=0.8)  
```


```{r}
ggplot(data, aes(x=price, y=sales)) + geom_point(size=2, shape=1) + geom_smooth(se = TRUE, method = "loess") 
```
# 05 Best Transformations acepack

```{r}
library(acepack)

data   = read.csv("https://raw.githubusercontent.com/PacktPublishing/R-Statistics-Cookbook/master/Chapter05/house_prices.csv") 
x      = data[,2:7] 
y      = data[,1] 

lm_model = lm(data=data,Property_price~ size  + number.bathrooms + number.bedrooms + number.entrances  +  size_balcony + size_entrance) 
summary(lm_model) 
```
```{r}
ace_model = ace(x,y) 
ace_model$rsq 
```
```{r}
par(mfrow=c(1,2))
plot(ace_model$x[1,],ace_model$tx[,1],xlab="untransformed size_entrance",ylab="transformed size_entrance") 
plot(ace_model$x[5,],ace_model$tx[,5],xlab="untransformed size_balcony",ylab="transformed size_balcony") 
```
# 06 Nonparametric Multivariate Tests npmv

```{r}
library(npmv)
nonpartest(Sepal.Length | Sepal.Width | Petal.Length | Petal.Width ~ Species, data = iris, permreps = 2000) 
```


```{r}
ssnonpartest(Sepal.Length | Sepal.Width | Petal.Length | Petal.Width ~ Species, data = iris, test = c(1, 0, 0, 0), alpha = 0.05, factors.and.variables = TRUE) 
```
# 07 SemiPar

```{r}
library(SemiPar) 
set.seed(10)

x1       = rnorm(100,20,6) 
x2       = runif(100,1,8) 
y        = 10 + x1 + x2 + rnorm(100,0,5)  
data_sim = data.frame(x1=x1,x2=x2,y=y) 
par(mfrow=c(1,2))

attach(data_sim)
fit <- spm(y ~ x1 +x2) 
summary(fit)
plot(fit) 
```

```{r}
x1       = rnorm(100,20,6) 
x2       = runif(100,1,8) 
y        = 10 + x1 + 150*exp(-x2) + rnorm(100,0,5)  
data_sim = data.frame(x1=x1,x2=x2,y=y) 
fit <- spm(data_sim$y ~  f(data_sim$x1)+f(data_sim$x2)) 
summary(fit) 
```

```{r}
plot(fit) 
```

```{r}
fit <- spm(data_sim$y ~ data_sim$x1 + f(data_sim$x2)) 
summary(fit) 
```

```{r}
fit <- spm(data_sim$y ~ data_sim$x1 + f(data_sim$x2,spar=20)) 
summary(fit) 
```

```{r}
plot(fit)
```

```{r}
fit <- spm(data_sim$y ~ data_sim$x1 + f(data_sim$x2,df=6)) 
summary(fit) 
```

```{r}
plot(fit)
```

