---
title: "R Stats Cookbook - 10 Bayesian Networks and HMMs"
output: html_notebook
---

# 02 Conditional Independence Tests

```{r}
library(bnlearn) 
library(ggplot2)

data = read.csv("https://raw.githubusercontent.com/PacktPublishing/R-Statistics-Cookbook/master/Chapter10/employee_data.csv")[-1] 
dag     = model2network("[Area][travel_time|Area][performance|travel_time:diet_quality][Recently_had_child][Sleep_quality|Recently_had_child:Area][diet_quality|Sleep_quality]")

plot(dag) 
```
# 04 BNs with bnviewer

```{r}
library("bnviewer")
library("bnlearn")

data           = read.csv("https://archive.ics.uci.edu/ml/machine-learning-databases/abalone/abalone.data")
colnames(data) = c("sex","length","diameter","height","whole_weight","shucked_weight","viscera_weight","shell_weight","rings") 
data$rings     = log(data$rings)

dag     = model2network("[sex][length|sex][diameter|sex][height|sex][whole_weight|length:diameter:height][shucked_weight|length:diameter:height][viscera_weight|length:diameter:height][shell_weight|length:diameter:height][rings|whole_weight:shucked_weight:viscera_weight:shell_weight]")
parm    = list(nodes = nodes(dag), arcs = arcs(dag),col = "black", textCol = "black")

viewer(dag,
       bayesianNetwork.width    = "100%",
       bayesianNetwork.height   = "80vh",
       bayesianNetwork.layout   = "layout_with_sugiyama",
       bayesianNetwork.title    = "Abalone network",
       bayesianNetwork.subtitle = "User defined network",
       bayesianNetwork.footer   = "Fig. 1 - live diagram"
)

viewer(dag,
       bayesianNetwork.width    = "100%",
       bayesianNetwork.height   = "80vh",
       bayesianNetwork.layout   = "layout_as_tree",
       bayesianNetwork.title    = "Abalone network",
       bayesianNetwork.subtitle = "User defined network",
       bayesianNetwork.footer   = "Fig. 1 - live diagram"
)
```


```{r}
library('depmixS4') 

datas           = read.csv("https://raw.githubusercontent.com/PacktPublishing/R-Statistics-Cookbook/master/Chapter10/hist_PAM20190304.csv")[5] 
returns        = diff(datas$cierre)/datas$cierre[-length(datas$cierre)] 
plot(returns,type="l") 
```


```{r}
returns        = data.frame(returns =returns) 
hist(returns$returns,main="Histogram of returns") 
```


```{r}
hmm <- depmix(returns ~ 1, family = gaussian(), nstates = 2, data=data.frame(returns=returns)) 
hmmfit <- fit(hmm, verbose = FALSE) 
post_probs <- posterior(hmmfit) 
layout(1:4) 
```


```{r}
plot(datas$cierre,type="l") 
```


```{r}
plot(returns$returns,type="l") 
```


```{r}
plot(post_probs$state, type='s', main='True Regimes', xlab='', ylab='Regime') 
```

```{r}
matplot(post_probs[,-1], type='l', main='Regime Posterior Probabilities', ylab='Probability') 
legend(x='topright', c('Flat-Bear','Bull'), fill=1:3, bty='n')
```

```{r}
hmm <- depmix(returns ~ 1, family = gaussian(), nstates = 3, data=data.frame(returns=returns)) 
```

