---
title: "MMLWRE 08 Cluster Analysis"
output: html_notebook
---

```{r}
library(cluster) #conduct cluster analysis
library(compareGroups) #build descriptive statistic tables
library(HDclassif) #contains the dataset
library(NbClust) #cluster validity measures
library(sparcl) #colored dendrogram
```

```{r}
data(wine)
str(wine)
```


```{r}
names(wine) <- c("Class", "Alcohol", "MalicAcid", "Ash", "Alk_ash",
                 "magnesium", "T_phenols", "Flavanoids", "Non_flav",
                 "Proantho", "C_Intensity", "Hue", "OD280_315", "Proline")
names(wine)
```


```{r}
df <- as.data.frame(scale(wine[, -1]))
str(df)
table(wine$Class)
```


```{r}
numComplete <- NbClust(df, distance = "euclidean", 
                       min.nc = 2, max.nc = 6, 
                       method = "complete", index = "all")
numComplete$Best.nc
```


```{r}
dis <- dist(df, method = "euclidean")
hc <- hclust(dis, method = "complete")
plot(hc, hang = -1,labels = FALSE, main = "Complete-Linkage")
```


```{r}
comp3 <- cutree(hc, 3)
ColorDendrogram(hc, y = comp3, main = "Complete", branchlength = 50)
```


```{r}
table(comp3)
table(comp3, wine$Class)
```


```{r}
numWard <- NbClust(df, diss = NULL, distance = "euclidean", 
        min.nc = 2, 
        max.nc = 6, 
        method= "ward.D2", 
        index = "all")

hcWard <- hclust(dis, method = "ward.D2")
plot(hcWard, hang = -1, labels = FALSE, main = "Ward's-Linkage")
```


```{r}
ward3 <- cutree(hcWard, 3)
table(ward3, wine$Class)    
```


```{r}
table(comp3, ward3)
```


```{r}
aggregate(wine[, -1], list(comp3), mean)
```


```{r}
aggregate(wine[, -1], list(ward3), mean)
```


```{r}
par(mfrow = c(1, 2))

boxplot(wine$Proline ~ comp3, 
        main = "Proline by Complete Linkage")
boxplot(wine$Proline ~ ward3, 
        main = "Proline by Ward's Linkage")
```


```{r}
set.seed(1234)
km <- kmeans(df, 3, nstart = 25)
table(km$cluster)
km$centers
```


```{r}
# wine$km_cluster <- km$cluster
boxplot(wine$Alcohol ~ km$cluster, 
        main = "Alcohol Content, K-Means")
```


```{r}
boxplot(wine$Alcohol ~ ward3, 
        main = "Alcohol Content, Ward's")
```


```{r}
table(km$cluster, wine$Class)
```


```{r}
wine$Alcohol <- as.factor(ifelse(df$Alcohol > 0, "High", "Low"))

disMatrix <- daisy(wine[, -1], metric = "gower")  
set.seed(123)
pamFit <- pam(disMatrix, k = 3)
table(pamFit$clustering)
table(pamFit$clustering, wine$Class)
```

```{r}
wine$cluster <- pamFit$clustering

group <- compareGroups(cluster ~ ., data = wine) 
clustab <- createTable(group) 
clustab
# export2csv(clustab, file = "wine_clusters.csv")
```


```{r}
library(randomForest)
set.seed(1)
rf <- randomForest(x = wine[, -1], ntree = 2000, proximity = T)
rf
```


```{r}
dim(rf$proximity)
rf$proximity[1:5, 1:5]
importance(rf)
```


```{r}
dissMat <- sqrt(1 - rf$proximity)
dissMat[1:2, 1:2]
```


```{r}
set.seed(123)
pamRF <- pam(dissMat, k = 3)
table(pamRF$clustering)
table(pamRF$clustering, wine$Class)
```

