---
title: "R Templates - 01B Visualization"
output: html_notebook
---

# Andrews Curves

```{r}
library(andrews)
# load dataset
data(iris)
# generate andres curves
andrews(iris, clr=5, ymax=3)
```
# Barplot

```{r}
library(mlbench)
# load the dataset
data(BreastCancer)
# create a bar plot of each categorical attribute
par(mfrow=c(2,4))
for(i in 2:9) {
	counts <- table(BreastCancer[,i])
	name <- names(BreastCancer)[i]
	barplot(counts, main=name)
}
```
# Boxplot by Class

```{r}
library(caret)
# load the iris dataset
data(iris)
# box and whisker plots for each attribute by class value
x <- iris[,1:4]
y <- iris[,5]
featurePlot(x=x, y=y, plot="box")
```
# Correlation Plot

```{r}
library(corrplot)
# load the data
data(iris)
# calculate correlations
correlations <- cor(iris[,1:4])
# create correlation plot
corrplot(correlations, method="circle")
```
# Density Plot

```{r}
library(lattice)
# load dataset
data(iris)
# create a panel of simpler density plots by attribute
par(mfrow=c(1,4))
for(i in 1:4) {
	plot(density(iris[,i]), main=names(iris)[i])
}
```
# Density Plot by Class

```{r}
library(caret)
# load the data
data(iris)
# density plots for each attribute by class value
x <- iris[,1:4]
y <- iris[,5]
scales <- list(x=list(relation="free"), y=list(relation="free"))
featurePlot(x=x, y=y, plot="density", scales=scales)
```
# Histogram

```{r}
data(iris)
# create histograms for each attribute
par(mfrow=c(1,4))
for(i in 1:4) {
	hist(iris[,i], main=names(iris)[i])
}
```
# Missing Plot

```{r}
library(Amelia)
library(mlbench)
# load dataset
data(Soybean)
# create a missing map
missmap(Soybean, col=c("black", "grey"), legend=FALSE)
```
# Parallel Coordinates

```{r}
library(MASS)
# load dataset
data(iris)
# convert data frame to matrix
iris_matrix <- data.matrix(iris)
parcoord(iris_matrix)
```
# Sammons

```{r}
library(MASS)
# load dataset
data(iris)
# remove duplicates
clean <- unique(iris)
# split out numerical inputs
x <- data.matrix(clean[, 1:4])
# create a sammon mapping
mapping <- sammon(dist(x))
# plot mapping by class
plot(mapping$points, type="n")
text(mapping$points, labels=clean[,5])
```
# Scatterplot Matrix

```{r}
data(iris)
# pair-wise scatterplots of all 4 attributes
pairs(iris)
```
# Scatterplot Matrix by Class

```{r}
data(iris)
# pair-wise scatterplots colored by class
pairs(Species~., data=iris, col=iris$Species)
```
