---
title: "Data Viz 08 3D Plots"
output: html_notebook
---

```{r}
library(ggplot2)
ggplot(data = cars, aes(x = speed, y = dist)) + 
  geom_density_2d(aes(colour = ..level..))
## STEP 2: USE stat_density_2d() TO DRAW POLYGONS INSTEAD
ggplot(cars, aes(x = speed, y = dist)) + 
  stat_density_2d(geom = 'polygon',
                  aes(fill = ..level..),
                  colour = 'yellow') + 
  ylim(-10,110) + xlim(0,30) +
  coord_cartesian(xlim = c(5,25), ylim = c(0,100))
```
```{r}
## STEP 1:  USE bins TO SET THE LEVELS
library(ggplot2)
ggplot(data = cars, aes(x = speed, y = dist)) + 
  geom_density_2d(aes(colour = ..level..), bins = 15)
## STEP 2: USE binwidth TO SET THE LEVELS
ggplot(data = cars, aes(x = speed, y = dist)) + 
  geom_density_2d(aes(colour = ..level..), binwidth = .0005)
```


```{r}
## STEP 1: DESING A CONTOUR PLOT
library(ggplot2)
plot <- ggplot(data = cars, aes(x = speed, y = dist)) + 
  geom_density_2d(aes(colour = ..level..))
## STEP 2: INPUT IT INTO direct.label()
library(directlabels)
direct.label(plot, list('top.pieces', colour = 'black'))
```


```{r}
library(ggplot2)
ggplot(data = cars, aes(x = speed, y = dist)) +
  stat_bin_2d(aes(fill = ..count..), 
              binwidth = c(5,15),
              colour = 'green',
              size = 1.05) +
  stat_bin_2d(geom = 'text', aes(label = ..count..), 
              binwidth = c(5,15), colour = 'white',
              size = 16)
```


```{r}
library(ggplot2)
ggplot(data = cars, aes(x = speed, y = dist)) + 
  stat_density_2d(aes(fill = ..density..),
                  geom = 'raster', contour = F) + 
  geom_density_2d(colour =  'white')
```


```{r}
## STEP 1: RASTER WITH DEFAULT COLORS
library(ggplot2)
ggplot(data = cars, aes(x = speed, y = dist)) + 
  stat_density_2d(aes(fill = ..density..),
                  geom = 'raster', contour = F)
## STEP 2: PICK ANOTHER SET OF COLORS
ggplot(data = cars, aes(x = speed, y = dist)) + 
  stat_density_2d(aes(fill = ..density..),
                  geom = 'raster', contour = F) +
  scale_fill_distiller(trans = 'reverse')
```


```{r}
## STEP 1: COMPUTE DATA
cars_d <- MASS::kde2d(cars$speed, cars$dist, n =50)
## STEP 2: DRAW 3D SURFACE USING plotly
library(plotly)
plot_ly(x = cars_d$x, 
        y = cars_d$y, 
        z = cars_d$z) %>% 
  add_surface()
```


```{r}
## STEP 1: DRAW BASE CONTOUR PLOT
library(ggplot2)
h1 <- ggplot(cars, aes(x = speed, y = dist)) +
  stat_density_2d(aes(colour = ..level..), size = 1.2) +
  theme_minimal()
## STEP 2: PICK A BETTER COLOR SCALE
h2 <- h1 + scale_colour_distiller(direction = 1, name = 'density', 
                                  breaks = seq(0.0002,0.0014,0.0002), 
                                  labels = format(seq(0.0002,0.0014,0.0002),
                                                  scientific = F))
## STEP 3: REWRITE AXES LABELS
h3 <- h2 + xlab('speed (mph)') + ylab('distance (ft)')
## STEP 4: GROW AXES BIGGER
h4 <- h3 + scale_y_continuous(breaks = seq(0,130,10), 
                         labels = seq(0,130,10),
                         minor_breaks = 0) +
  scale_x_continuous(breaks = seq(4,26,2),
                     labels = seq(4,26,2),
                     minor_breaks = 0)
## STEP 5: MOVE LEGENDS AND RESIZE TEXTS IN GENERAL
h5 <- h4 +  theme(legend.position = c(.2,.75),
  legend.background = element_rect(color = "black", 
                                   size = .2, 
                                   linetype = "solid"),
        legend.text = element_text(size = 13),
        legend.title = element_text(size = 14),
        axis.text = element_text(size = 15),
        axis.title = element_text(size = 18))
## STEP 6: AVOID CONFUSING LEGENDS 
h5 + guides(colour = guide_legend(title.vjust = .1))
```


