---
title: "Data Viz 04 One Variable"
output: html_notebook
---

```{r}
library(ggplot2) ; library(HistData)
gg2_Mich <- ggplot(Michelson, aes(x = velocity + 299000))
gg2_Mich + geom_histogram()
```
```{r}
library(HistData)
library(ggvis)
ggv_Mich <- ggvis(Michelson, x = ~velocity + 299000)
ggv_Mich %>% layer_histograms()
library(plotly)
pl_Mich <- plot_ly(Michelson, x = ~velocity + 299000, type = 'histogram')
pl_Mich
```


```{r}
library(ggplot2)
gg2_petal <- ggplot(data = iris, aes( x = Petal.Length, fill = Species))
gg2_petal + geom_density(alpha = .5) + xlim(.75,7.5)
```


```{r}
library(ggvis)
ggv_petal <- iris %>% group_by(Species) %>% ggvis(~Petal.Length, fill = ~Species)
ggv_petal %>% layer_densities()
```


```{r}
library(dplyr)
data_setosa <- iris %>% filter(Species == 'setosa') %>% pull(Petal.Length) %>% density()
data_setosa <- data.frame(Petal.Length = data_setosa$x,density = data_setosa$y)
data_versicolor <- iris %>% filter(Species == 'versicolor') %>% pull(Petal.Length) %>% density()
data_versicolor <- data.frame(Petal.Length = data_versicolor$x,density = data_versicolor$y)
data_virginica <- iris %>% filter(Species == 'virginica') %>% pull(Petal.Length) %>% density()
data_virginica <- data.frame(Petal.Length = data_virginica$x,density = data_virginica$y)

library(plotly)
pl_petal <- plot_ly(data = data_setosa, x = ~Petal.Length, y = ~density, type = 'scatter', mode = 'lines', fill = 'tozeroy')
pl_petal %>% add_trace(data = data_versicolor) %>% add_trace(data = data_virginica)
```


```{r}
library(DAAG) ; library(ggplot2)
ggplot(anesthetic, aes(x = conc, fill = factor(move))) + 
  geom_dotplot(binwidth = .2, binpositions = 'all', stackgroups = T) + coord_fixed(ratio = 1.4) +
  scale_y_continuous(name = NULL, breaks = NULL)
```


```{r}
library(DAAG); library(ggplot2)
ggplot(anesthetic, aes(x = factor(conc), fill = factor(move))) + 
  geom_dotplot(binpositions = 'all', stackgroups = T, dotsize = 6) +
  scale_y_continuous(name = NULL, breaks = NULL)
```



