---
title: "BNWER Ch04 - Theory and Algorithms for Bayesian Networks"
output: html_notebook
---

```{r}
library(bnlearn)
options(width = 65)
X <- paste("[X1][X3][X5][X6|X8][X2|X1][X7|X5][X4|X1:X2]",
      "[X8|X3:X7][X9|X2:X7][X10|X1:X9]", sep = "")
dag <- model2network(X)
skel <- skeleton(dag)
vstructs(dag)
```

```{r}
cp1 <- cpdag(dag)
dag2 <- dag
dag2 <- set.arc(dag2, "X7", "X5")
dag2 <- set.arc(dag2, "X4", "X2")
dag2 <- set.arc(dag2, "X1", "X2")
dag2 <- set.arc(dag2, "X1", "X4")
cp2 <- cpdag(dag2)
all.equal(cp1, cp2)
```


```{r}
dsep(dag, x = "X9", y = "X5", z = c("X2", "X7", "X10"))
```


```{r}
mb(dag, node = "X9")
mb(dag, node = "X7")
```


```{r}
par.X9 <- parents(dag, node = "X9")
ch.X9 <- children(dag, node = "X9")
```


```{r}
sp.X9 <- sapply(ch.X9, parents, x = dag)
```


```{r}
sp.X9 <- sp.X9[sp.X9 != "X9"]
unique(c(par.X9, ch.X9, sp.X9))
```


```{r}
V <- setdiff(nodes(dag), "X9")
S <- mb(dag, "X9")
sapply(setdiff(V, S), dsep, bn = dag, y = "X9", z = S)
```


```{r}
V <- setdiff(nodes(dag), "X7")
S <- mb(dag, "X7")
sapply(setdiff(V, S), dsep, bn = dag, y = "X7", z = S)
```


```{r}
belongs <- logical(0)
for (node in S)
  belongs[node] <- "X7" %in% mb(dag, node)
belongs
```


```{r}
mg1 <- moral(dag)

all.equal(moral(dag),
          moral(set.arc(dag, from = "X7", to = "X3")))
```


```{r}
mg2 <- dag
vs <- vstructs(dag)
for (i in seq(nrow(vs)))
  mg2 <- set.edge(mg2, from = vs[i, "X"], to = vs[i, "Y"],
           check.cycles = FALSE)
```


```{r}
mg2 <- skeleton(mg2)
all.equal(mg1, mg2)
```


```{r}
set.seed(4567);
dag.bnlearn <- model2network("[G][E][V|G:E][N|V][W|V][C|N:W]")
disE <- list(coef = c("(Intercept)" = 50), sd = 10)
disG <- list(coef = c("(Intercept)" = 50), sd = 10)
disV <- list(coef = c("(Intercept)" = -10.35534,
             E = 0.70711, G = 0.5), sd = 5)
disN <- list(coef = c("(Intercept)" = 45, V = 0.1), sd = 9.949874)
disW <- list(coef = c("(Intercept)" = 15, V = 0.7), sd = 7.141428)
disC <- list(coef = c("(Intercept)" = 0, N = 0.3, W = 0.7),
             sd = 6.25);
dis.liste = list(E = disE, G = disG, V = disV, N = disN,
                 W = disW, C = disC)
gbn.bnlearn <- custom.fit(dag.bnlearn, dist = dis.liste)
cropdata1 <- cpdist(gbn.bnlearn, nodes = nodes(gbn.bnlearn),
                    evidence = TRUE, n = 200)

bn.cor <- gs(cropdata1, test = "cor", alpha = 0.05)
modelstring(bn.cor)

```


```{r}
bn.zf <- gs(cropdata1, test = "zf", alpha = 0.05)
bn.mc <- gs(cropdata1, test = "mc-cor", B = 1000)
all.equal(bn.cor, bn.zf)
all.equal(bn.cor, bn.mc)
```


```{r}
bn.iamb <- iamb(cropdata1, test = "cor", alpha = 0.05)
all.equal(bn.cor, bn.iamb)
```


```{r}
ci.test("N", "V", test = "cor", data = cropdata1)
ci.test("N", "V", "C", test = "cor", data = cropdata1)
```


```{r}
bn.cor <- gs(cropdata1, test = "cor", alpha = 0.05, 
            whitelist = c("V", "N"))
all.equal(bn.cor, dag.bnlearn)
```


```{r}
survey <- read.table("https://raw.githubusercontent.com/pw598/Legacy-Notebooks/main/data/survey.txt", header = TRUE)
```


```{r}
survey$A = as.factor(survey$A)
survey$R = as.factor(survey$R)
survey$E = as.factor(survey$E)
survey$O = as.factor(survey$O)
survey$S = as.factor(survey$S)
survey$T = as.factor(survey$T)
survey
```


```{r}
learned <- hc(survey, score = "bic")
modelstring(learned)
score(learned, data = survey, type = "bic")
```


```{r}
survey.dag <- model2network("[A][S][E|A:S][O|E][R|E][T|O:R]")
learned.start <- hc(survey, score = "bic", start = survey.dag)
modelstring(learned.start)
all.equal(cpdag(learned), cpdag(learned.start))
```


```{r}
set.seed(1234)
hc(survey, score = "bic", start = random.graph(names(survey)))
mmhc(survey)
```


```{r}
rsmax2(survey, restrict = "mmpc", maximize = "hc")
```


```{r}
rsmax2(survey, restrict = "si.hiton.pc", test = "x2",
  maximize = "tabu", score = "bde", 
  maximize.args = list(iss = 5))
```


```{r}
res <- model2network("[A][S][E|A:S][O|E][R|E][T|O:R]")

A.lv <- c("young", "adult", "old")
S.lv <- c("M", "F")
E.lv <- c("high", "uni")
O.lv <- c("emp", "self")
R.lv <- c("small", "big")
T.lv <- c("car", "train", "other")

A.prob <- matrix(c(0.30, 0.50, 0.20), ncol = 3,
            dimnames = list(c(""), A = A.lv))

S.prob <- matrix(c(0.60, 0.40), ncol = 2,
            dimnames = list(c(""), S = S.lv))

E.prob <- array(c(0.75, 0.25, 0.72, 0.28, 0.88, 0.12, 0.64, 0.36,
            0.70, 0.30, 0.90, 0.10), dim = c(2, 3, 2),
            dimnames = list(E = E.lv, A = A.lv, S = S.lv))

O.prob <- matrix(c(0.96, 0.04, 0.92, 0.08), nrow = 2,
            dimnames = list(O = O.lv, E = E.lv))

R.prob <- matrix(c(0.25, 0.75, 0.20, 0.80), nrow = 2,
            dimnames = list(R = R.lv, E = E.lv))

T.prob <- array(c(0.48, 0.42, 0.10, 0.56, 0.36, 0.08, 0.58, 0.24,
            0.18, 0.70, 0.21, 0.09), dim = c(3, 2, 2),
            dimnames = list(T = T.lv, O = O.lv, R = R.lv))

res3 <- model2network("[A][S][E|A:S][O|E][R|E][T|O:R]")

tdp <- list(A = A.prob, S = S.prob, E = E.prob, O = O.prob, R = R.prob, T = T.prob)
bn <- custom.fit(res3, tdp)
set.seed(123)
options(digits = 5)



cpquery(bn, event = (S == "M") & (T == "car"),
          evidence = (E == "high"), n = 10^6)
```


```{r}
particles <- rbn(bn, 10^6)
head(particles, n = 5)
```


```{r}
partE <- particles[(particles[, "E"] == "high"), ]
nE <- nrow(partE)
partEq <- 
  partE[(partE[, "S"] == "M") & (partE[, "T"] == "car"), ]
nEq <- nrow(partEq)
nEq/nE
```


```{r}
mutbn <- mutilated(bn, list(E = "high"))
mutbn$E
```


```{r}
set.seed(123)
particles <- rbn(bn, 10^6)
partQ <- particles[(particles[, "S"] == "M") & 
                  (particles[, "T"] == "car"), ]
nQ <- nrow(partQ)
nQ/10^6
```


```{r}
w <- logLik(bn, particles, nodes = "E", by.sample = TRUE)
wEq <- sum(exp(w[(particles[, "S"] == "M") & 
                (particles[, "T"] == "car")]))
wE <- sum(exp(w))
wEq/wE
```


```{r}
set.seed(678)
cpquery(bn, event = (S == "M") & (T == "car"),
          evidence = list(E = "high"), method = "lw")
```

```{r}
data(marks)
head(marks)
```


```{r}
latent <- factor(c(rep("A", 44), "B", 
                  rep("A", 7), rep("B", 36)))
modelstring(hc(marks[latent == "A", ]))
modelstring(hc(marks[latent == "B", ]))
modelstring(hc(marks))
```


```{r}
dmarks <- discretize(marks, breaks = 2, method = "interval")
modelstring(hc(cbind(dmarks, LAT = latent)))
```

