---
title: "MLWR Cookbook 05 Regression"
output: html_notebook
---

```{r}
library(car)
data(Quartet)
str(Quartet)
```
```{r}
plot(Quartet$x, Quartet$y1)
lmfit = lm(y1~x, Quartet) 
abline(lmfit, col='red')  
```

```{r}
lmfit
```


```{r}
plot(Quartet$x, Quartet$y1)
```
```{r}
plot(Quartet$x, Quartet$y1)
lmfit2 = lsfit(Quartet$x,Quartet$y1)
abline(lmfit2, col="red")  
```


```{r}
summary(lmfit)
```

```{r}
lmfit = lm(y1~x, Quartet)
newdata = data.frame(x = c(3,6,15))
predict(lmfit, newdata, interval="confidence", level=0.95)
predict(lmfit, newdata, interval="predict")
par(mfrow=c(2,2))
plot(lmfit)
```





```{r}
plot(cooks.distance(lmfit))
```


```{r}
head(Prestige)
```


```{r}
str(Prestige)
```


```{r}
attach(Prestige)
model = lm(income~prestige+women)
```


```{r}
summary(model)
```


```{r}
coefficients(model)
```


```{r}
confint(model, level=0.95)
```


```{r}
fitted(model)
```


```{r}
residuals(lmfit)
```


```{r}
anova(model)
```


```{r}
vcov(model)
```


```{r}
influence(model) # Diagnose quality of regression fits
```


```{r}
model = lm(income ~ prestige + women, Prestige)
newdat = data.frame(prestige = c(75,80), women=c(14,13)) 
predict(model, newdata = newdat)
predict(model, newdata = newdat, interval="predict")
plot(Quartet$x, Quartet$y2)
```


```{r}
lmfit = lm(Quartet$y2~poly(Quartet$x,2))
lines(sort(Quartet$x), lmfit$fit[order(Quartet$x)], col = "red")
plot(Quartet$x, Quartet$y2)
```


```{r}
lmfit = lm(Quartet$y2~ I(Quartet$x)+I(Quartet$x^2))
plot(Quartet$x, Quartet$y3)
```


```{r}
library(MASS)
lmfit = rlm(Quartet$y3~Quartet$x)
abline(lmfit, col="red")
plot(Quartet$x, Quartet$y3)
```


```{r}
str(SLID)
```


```{r}
plot(SLID$wages ~ SLID$language)
plot(SLID$wages ~ SLID$age)
plot(SLID$wages ~ SLID$education)
plot(SLID$wages ~ SLID$sex)
```


```{r}
lmfit = lm(wages ~ ., data = SLID)
summary(lmfit)
```


```{r}
lmfit = lm(wages ~ age + sex + education, data = SLID)
summary(lmfit)
```


```{r}
par(mfrow=c(2,2))
plot(lmfit) 
```


```{r}
lmfit = lm(log(wages) ~ age + sex + education, data = SLID)
plot(lmfit)
```


```{r}
vif(lmfit)
```


```{r}
sqrt(vif(lmfit)) > 2
```


```{r}
lmfit1 = glm(wages ~ age + sex + education, data = SLID, family=gaussian)
summary(lmfit1)
```


```{r}
lmfit2 = lm(wages ~ age + sex + education, data = SLID)
summary(lmfit2)
```


```{r}
anova(lmfit1, lmfit2)
```


```{r}
data(warpbreaks)
head(warpbreaks)
```


```{r}
rs1 = glm(breaks ~ tension, data=warpbreaks, family="poisson")
summary(rs1)
```


```{r}
head(mtcars$vs)
```


```{r}
lm1 = glm(vs ~ hp+mpg+gear,data=mtcars, family=binomial)
summary(lm1)
```


```{r}
install.packages("mgcv")
library(mgcv)
install.packages("MASS")
library(MASS)
attach(Boston)
str(Boston)
```


```{r}
fit = gam(dis ~ s(nox))
summary(fit)
```


```{r}
plot(nox, dis)
```


```{r}
x = seq(0, 1, length = 500)
y = predict(fit, data.frame(nox = x))
lines(x, y, col = "red", lwd = 2)
plot(fit)
```


```{r}
fit2=gam(medv~crim+zn+crim:zn, data=Boston)
vis.gam(fit2)
gam.check(fit)
```
