---
title: "MLWR Cookbook 12 Association Rules"
output: html_notebook
---

```{r}
library(arules)
tr_list = list(c("Apple", "Bread", "Cake"),
               c("Apple", "Bread", "Milk"),
               c("Bread", "Cake", "Milk"))
names(tr_list) = paste("Tr",c(1:3), sep = "")
trans = as(tr_list, "transactions")
trans
```
```{r}
tr_matrix = matrix(
     c(1,1,1,0,
     1,1,0,1,
     0,1,1,1), ncol = 4)
dimnames(tr_matrix) =  list(
 paste("Tr",c(1:3), sep = ""),
   c("Apple","Bread","Cake", "Milk")
   )
trans2 =  as(tr_matrix, "transactions")
trans2
```


```{r}
Tr_df = data.frame(
  TrID= as.factor(c(1,2,1,1,2,3,2,3,2,3)),
  Item = as.factor(c("Apple","Milk","Cake","Bread",
   "Cake","Milk","Apple","Cake","Bread","Bread")))
trans3 = as(split(Tr_df[,"Item"], Tr_df[,"TrID"]), "transactions")
trans3
```


```{r}
LIST(trans)
```


```{r}
summary(trans)
```


```{r}
inspect(trans)
```


```{r}
filter_trains = trans[size(trans) >=3]
inspect(filter_trains)
```


```{r}
image(trans)
```


```{r}
itemFrequencyPlot (trans)
```


```{r}
data(Groceries)
itemFrequencyPlot(Groceries, support = 0.1, cex.names=0.8, topN=5)
```


```{r}
rules = apriori(Groceries, parameter = list(supp = 0.001, conf = 0.5, target= "rules"))
summary(rules)
```


```{r}
inspect(head(rules))
```


```{r}
rules=sort(rules, by="confidence", decreasing=TRUE)
inspect(head(rules))
```


```{r}
library('arulesViz')
soda_rule=apriori(data=Groceries, parameter=list(supp=0.001,conf = 0.1, minlen=2), appearance = list(default="rhs",lhs="soda"))
plot(sort(soda_rule, by="lift"), method="graph", control=list(type="items"))
```

```{r}
plot(soda_rule, method="grouped")
```


```{r}
frequentsets=eclat(Groceries,parameter=list(support=0.05,maxlen=10))
summary(frequentsets)
```


```{r}
inspect(sort(frequentsets,by="support")[1:10])
```


```{r}
tmp_data=list(c("A"),
              c("A","B","C"),
              c("A","C"),
              c("D"),
              c("C","F"),
              c("A","D"),
              c("C"),
              c("B","C"),
              c("A","E"),
              c("E","F"),
              c("A","B"),
              c("D","F"),
              c("C"),
              c("B"),
              c("E"),
              c("G"),
              c("A","F"),
              c("C"),
              c("B"),
              c("C"))
names(tmp_data) = paste("Tr",c(1:20), sep = "")
trans =  as(tmp_data,"transactions")
transactionInfo(trans)$sequenceID=c(1,1,1,1,1,2,2,2,2,3,3,3,3,3,4,4,4,4,4,4)
transactionInfo(trans)$eventID=c(10,20,30,40,50,10,20,30,40,10,20,30,40,50,10,20,30,40,50,60)
trans
```


```{r}
inspect(head(trans))
```


```{r}
summary(trans)
```


```{r}
library(TraMineR)
data("mvad")
head(mvad)
```
```{r}
alphabet = seqstatl(mvad[,17:86])
fulllabel<- c("employment", "further education", "higher educa-tion","joblessness", "school", "training")
shortlabel<- c("EM", "FE", "HE", "JL", "SC", "TR")
seq_mvad<- seqdef(mvad[, 17:86], alphabet = alphabet,
                  states = shortlabel, labels = fulllabel, weights = mvad$weight,
                  xtstep = 6)
seq_mvad[1:2,]
```


```{r}
print(seq_mvad[1:2,],format="SPS")
```


```{r}
seqiplot(seq_mvad)
```


```{r}
seqfplot(seq_mvad)
```


```{r}
seqdplot(seq_mvad)
```


```{r}
seqmtplot(seq_mvad)
```


```{r}
seqiplot(seq_mvad, group = mvad$male)
```


```{r}
seqmtplot(seq_mvad, group = mvad$male)
```

```{r}
seqHtplot(seq_mvad)
```


```{r}
seqHtplot(seq_mvad, group = mvad$male)
```

